title: Claire Russell
#logo: relative path to image in github repo
description: 
ğŸ“Š Data Science Portfolio  

Welcome to my Data Science portfolio! This repository highlights projects that showcase my skills in data analysis, machine learning, visualisation, and statistical modelling. Each project includes code, documentation, and key insights.  

ğŸ“ Education  
Master of Applied Data Analytics  
The Australian National University  
ğŸ“… 2021 â€“ 2024  
ğŸ“š Specialisation in Computer Science  
ğŸ” Focus: Machine learning, statistical modelling, data for research  

Bachelor of International and Global Studies  
The University of Sydney  
ğŸ“… 2013 â€“ 2017  
ğŸŒ Major: Government and International Relations  

ğŸ’¼ Work Experience  
ğŸ” Data Analyst / Senior Data Analyst  
Department of Foreign Affairs and Trade (DFAT), Australia  
ğŸ“… 2023 â€“ Present  
ğŸŒ Canberra, ACT  
#show_downloads: true
theme: jekyll-theme-minimal
