site_name: Claire Russell
site_url: https://clairelouiser.github.io

theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: teal

plugins:
  - search
  - mkdocs-jupyter

markdown_extensions:
  - attr_list
  - md_in_html

extra_css:
  - assets/extra.css

nav:
  - Home: index.md
  - Projects:
      - Network Analysis:
          - Overview: projects/networks/index.md
          - Notebook: projects/networks/analysis.ipynb
      - Facial Emotion Recognition:
          - Overview: projects/emotion-recognition/index.md
          - Notebook: projects/emotion-recognition/analysis.ipynb

